using UnityEngine;
using System.Collections;

public enum EventID
{
    GAME_EVENT,
    ADD_PASSIVE,
    ADD_SKILL,
    CANCEL_SKILL,
    ON_ENEMY_DIE,
    ON_SKILL_PICKED,
    PLAYER_REVIE,
    ON_DIE,
    REVIVE_POPUP,
    PLAYER_REVIE_DONE,
    ON_END_WAVE,
    ON_NEW_WAVE,
    ON_NEXT_ARENA,
    ON_PAUSE,
    ON_ATTACK_HIT,
    UPDATE_CURRENCY,
    UPDATE_KEY,
    UPDATE_ADS,
    VICTORY_POPUP,
    OPENKEYFREE_ADS,
    BUYITEM_IAP,

    RELOAD_INVENTORY,
    CHANGE_PAGE,

    ON_MODIFIER_EQUIPMENT,

    EFFECT_FLASH,

    MUTE_SOUND_BACKGROUND,
    MUTE_SOUND_EFFECT,
    PAUSE_SOUND,
    COUNT_ENEMY_TUTORIAL,
    ON_NEXT_STEP_TUTORIAL,
    ON_START_TUTORIAL_GAMEPLAY,
    ON_FINISH_TUTORIAL_GAMEPLAY,

    DAILY_LOGIN_ADS,
    SETUP_DATA_BEFORRE_SENDEVENT,
    REVIVE_ADS,
    X2_FINISH_GAME,   
    PASSIVE_REROLL,
    HEAL_SPECIAL,
    //
    LUCKYSPIN_SPECIAL,
    TEMPORARY_BOOSTER,
    CHECK_ADS_REVIVE,
    RELOAD_SHOWSTAT_EQUIPMENT,
    CHOOSE_SPIRIT,

    //ChangeImageHero
    CHANGE_WEAPON,
    CHANGE_ARMOR,
    CHANGE_CHARACTER,
    CHANGE_LOCALIZE_TEXT,
    
    ON_SHOW_ADS_SUCCESS,
    ON_WATCH_ADS_COMPLETE_SUCESS,
    ON_WATCH_ADS_FAIL,
    ON_BLOOD_DAMAGE,
    ON_X2_PASSIVE_CHOOSE,
    ON_BONUS_ENCOUNTER,
    ON_REFRESH_SHOP_LABYRIN,
    ON_RANDOM_ITEM_SHOP_LABYRIN,
    ON_BUY_ADSPASS,
    ON_BACK_ANDROID_BTN,
    ON_SEND_PRODUCT_IAP_ID,
    ON_BUY_SUCCESS_PRODUCT_IAP,
    ON_BUY_FAIL_PRODUCT_IAP,
    GET_PRICE_PRODUCT_ITEM,
    UPDATE_LEVELUP_ACCOUNT,
    CHANGE_VALUE_ACHIEVEMENT,
    ON_PROMO_ADS_COMBINE,
    ON_PROMO_ADS_ENHANCE,
    ON_PROMO_ADS_EXTRACT,
    ON_COLLECT_GEMPOT,
    ON_CHANGE_MODE_ARENA,
    ON_OPEN_FORGE_PACK_ADS,
    ON_CHANGE_ACHIEVEMENT_GAMEPLAY,
    ON_LOGIN_ONLINE_CLICK,
    ON_SAVE_DATA_LOGIN,

    LOAD_DATA_FIREBASE_ONLINE,
    SAVE_DATA_FIREBASE_ONLINE,








    ON_REDUCE_TIME_AUTO_ATTACK,
    REFRESH_COUNT_ADS_SYSTEM,









}
